### ISSUE TITLE
zsh: argument list too long: compare50

### ISSUE THREAD

**Issue by Erin-c** [cs50/compare50#15]
compare50 cash/submissions/* -a cash/archives/2012/fall/* cash/archives/2013/fall/* cash/archives/2014/fall/* cash/archives/2015/fall/* cash/archives/2015/spring/* cash/archives/2016/fall/* cash/archives/2017/fall/* cash/archives/2018/fall/* cash/archives/2018/spring/* cash/archives/honeypots/03052019/* 

Can I just do cash/archives/* even though that does not constitute one submission?

**Comment by crossroads1112** [comment]
No, and in fact intentionally not (otherwise how do we know what is an archive vs what is an archive containing directories)?

This was a concern when making everything submission a separate command line argument, but we chose to do it this way for flexibility/lack of ambiguity reasons. There is a workaround for this though:

The amount of space that the arguments are allowed to take up is 25% of the stack space on linux. You can increase the size of the stack to e.g. 65536 bytes (up from 8192) by running e.g. `ulimit -s 65536`, and then running compare50.


@Jelleas this is something we could nominally do in the compare50 bash script. Do you have thoughts on this? The immediate question is obviously what value to set it to, and this is of course dependent on the number of submissions to be compared (as well as the length of the filepaths I suppose), but we could maybe set it to some larger default?

**Comment by crossroads1112** [comment]
Okay, so this won't work on macs. In OSX the maximum amount of memory allocated for command line arguments is hard-coded. Increasing the stack size has no effect. Ugh...

Which means we are probably going to have to support something along the lines of #6. This raises some questions though. Nominally, archives OR submissions (OR distro I guess, but probably not) may need to be specified outside of command line arguments, so `stdin` is probably not ideal. Instead, we should probably somehow allow submissions/archives to be given in the form of a file containing file paths. It's not super clear to me what the best way to do this. We likely need a separate command line argument like `--archive-file` or something, but I'm not sure what the short-form command line equivalent would be (`-a` is taken of course). Similarly for regular submissions, but how should that work since these aren't normally specified via a command line argument? Or there could be a global flag which just tells compare50 to interpret any submissions as files containing paths to submissions rather than submissions themselves, but then you'd have to do both archives and submissions this way or neither.

Thoughts @Jelleas?

**Comment by dmalan** [comment]
Can a user not just quote such args, so that we can glob in compare50
itself? That’s what we do for render50, for instance.

**Comment by Jelleas** [comment]
One problem I foresee with supporting both quoted and already globbed args is that compare50 might receive well close to 10,000 filepaths (with a command like the above). Having to potentially try and glob each one seems costly.


I am increasingly in favor of supporting a config file that sets up a compare50 run (alongside the commandline args that we already support). Not only for circumventing the ARG_MAX limit, but also for this unwieldy long command:

```compare50 cash/submissions/* -a cash/archives/2012/fall/* cash/archives/2013/fall/* cash/archives/2014/fall/* cash/archives/2015/fall/* cash/archives/2015/spring/* cash/archives/2016/fall/* cash/archives/2017/fall/* cash/archives/2018/fall/* cash/archives/2018/spring/* cash/archives/honeypots/03052019/*```

A config file would make it easy to port to future instances of a course as you don't have to reinvent the command everytime. And in my vision you could extend the config file with runtime args, such that for instance you don't need to write all the archives over and over, or need to edit the file if you want to change just the type of comparison used.

**Comment by Erin-c** [comment]
@crossroads1112 @Jelleas @dmalan seems to work in Docker if I use `ulimit -s 65532` but isn't ideal to mount all of this to Docker first. Is there a timeline of when I can expect a fix?

**Comment by crossroads1112** [comment]
(well to be clear, you could probably shorten that command via `-a cash/archives/*/*` depending on what else you have in that directory, but still, point taken)

A config file nominally seems okay but when you specify paths, I presume you'd be doing so via patterns in which case whatever performance concern you had still applies. That said, I'm not _too_ worried about globbing in those instances. 

YAML, I presume?

Something like:

`cash.yaml`
```yaml
submissions: cash/submissions/*
archives:
  - cash/archives/2012/fall/*
  - cash/archives/2013/fall/*
distro: cash/distro/*
passes: # defaults to using all passes
 - exact
 - misspellings
```

`$ compare50 --config cash.yaml`

**Comment by crossroads1112** [comment]
@erin-c I don't have a concrete timeline for you at this moment, since it depends on what the solution ends up being. If you use `cli50`, your current directory should automatically be mounted, no? So if you run `cli50` in some parent directory of all of the submissions/archives you're going to need you shouldn't have to mount anything by hand, right? Obviously needing to run `cli50` is suboptimal (esp since compare50 isn't installed by default in it by default) though.

**Comment by Jelleas** [comment]
Retracting my earlier concerns about performance. Globbing ~100,000 filepaths, only increased runtime marginally by about one second, that is relatively speaking insignificant. That makes me in favor of supporting quoted patterns. Here's a working version to see for yourself: <https://github.com/cs50/compare50/tree/quoted_patterns>

On config then:

> YAML, I presume?
> 
> Something like:
> 
> `cash.yaml`
> 
> ```yaml
> submissions: cash/submissions/* # submissions/archives/distro can be lists or single strings
> archives:
>   - cash/archives/2012/fall/*
>   - cash/archives/2013/fall/*
> distro: cash/distro/*
> passes: # defaults to using all passes
>  - exact
>  - misspellings
> ```
> 
> `$ compare50 --config cash.yaml`

Nice! Just to add, besides running from a config directly you could also extend it by means of:

```compare50 --config cash.yaml -a cash/archives/2014/fall/*```

And overwrite those settings you can only specify once, like `passes`:

```compare50 --config cash.yaml -p misspellings exact```

Not to forget support for include/exclude:

```yaml
files:
  - !exclude "*"
  - !include "*.c"
```

> One small consideration: above we're obviously using relative paths for the submissions/archives. I assume we should take them to be relative to the directory containing the config file rather than relative to the user's current directory?

I agree with you there. You wouldn't want a config file to break just because your cwd changes.

**Comment by crossroads1112** [comment]
Support for include/exclude is surprisingly weird right now. There does not seem to be good way to utilize `lib50` at present. We can't do `lib50.config.load` because there's no `tool` here (we could fix this by making `tool` optional and if no `tool` is specified, it returns the whole config).

**Comment by crossroads1112** [comment]
Side note: if we can do the config file thing, I'd rather do that then the quoted paths. The quoted paths thing is a tad nin

**Comment by Jelleas** [comment]
Support for quoted patterns, yay/nay @crossroads1112 ?

**Comment by dmalan** [comment]
I'd vote for quoted patterns too, though also supporting `-c/--config` makes sense for more comfy/repeat users!

**Comment by crossroads1112** [comment]
Quoted patterns are now supported as of 6dc88e0
