### ISSUE TITLE
Move divider between side-by-side comparison view

### ISSUE THREAD

**Issue by Erin-c** [cs50/compare50#18]
Add support to drag middle divider between submissions left and right so as to make the review process easier

@dmalan @dlloyd09

**Comment by dmalan** [comment]
We use https://split.js.org/ for CS50 Lab, which seems to work well.

**Comment by crossroads1112** [comment]
Re split.js: We have to be careful about using external libraries in `compare50` because we have to copy the entirety of these libraries into every html file for which we need the functionality. (Can't keep one copy that all the html files reference since this would break if you wanted to send one file to someone else and can't just use a hosted version since we want matches to be viewable offline).

**Comment by Jelleas** [comment]
In my mind the need to be careful with external libraries is there because we are overloading each match file both for assessing potential plagiarism and for sharing the results. As @crossroads1112 noted we want matches to be viewable offline. As any match file can now be shared, everything needs to be in that file.  

If we seperate these concerns into an assessment view that can print to .pdf/.html, we could more liberally make use of libraries in this assessment view. As these libraries then don't need to be local, or at least not per file.

**Comment by dmalan** [comment]
Not sure this is a big deal? We handle this all the time with our offline-friendly docs. We just embed the dependencies in each HTML file, albeit redundantly. In this case, something like https://cdnjs.cloudflare.com/ajax/libs/split.js/1.5.9/split.min.js is only 5KB.

**Comment by Jelleas** [comment]
We added split.js and you can now move the divider.
