### ISSUE TITLE
-x '*' -i '*.ml' compares .yml in addition to .ml files

### ISSUE THREAD

**Issue by Erin-c** [cs50/compare50#21]
does -x and -i not handle exact matches

**Comment by crossroads1112** [comment]
That's not the issue. This came up when I was there in person. This is the problem you're facing:

`-x` and `-i` apply to files within a submission. However, if I tell compare50 that `foo.yaml` itself is a submission, `-x` isn't going to affect that. What's happening to you here is that you have a directory that looks like:

```
foo.yaml
student1/foo.ml
student2/foo.ml
```
and you're running (after the shell expands whatever wildcard you're using) `compare50 foo.yaml student1 student2 -x '*' -i '*.ml'`. This command is telling compare50 that the submissions it should compare are `foo.yaml`, `student1`, and `student2` and that _within those submissions_ it should only consider files that end in `.ml`. If there were an additional file _within_ the `student1` submission called, say, `student1/bar.yaml`, compare50 would exclude it. The similarity between `.yaml` and `.ml` here is completely coincidental.

**Comment by dmalan** [comment]
Hm, not sure that's the behavior we should adopt, though? Both `render50` and `zip`, on which `render50` based its `-x` and `-i` apply the whitelist and blacklist to all files provided:

```
$ zip -r archive.zip * -x "*.c"
  adding: bar/ (stored 0%)
  adding: baz/ (stored 0%)
```

I.e., I would also expect @Erin-c's command line to work as she expected? Especially if I ran

```
compare50 * -x '*' -i '*.ml'
```

or, presumably equivalently,

```
compare50 * -i '*.ml'
```

I would want to include only those files in `$CWD` that match the pattern? This would seem to allow me to have a bunch of files (not dirs) in `$CWD` that I want to compare, provided they share some file extension?

**Comment by crossroads1112** [comment]
As I understand it, `compare50` has fundamentally different constraints than `render50` does here. There are "two levels" that one could apply inclusion/exclusion rules for compare50: submissions, and the files within submissions. These are two distinct sets.  With render50, you give it a pattern and then the inclusion/exclusion rules serve to refine that pattern. In principle (depending on how comprehensive the globbing syntax is), one could use render50 without the inclusion/exclusion flags without a losing any functionality (at the cost of writing more complex patterns initially). This is not the case for compare50. With compare50, you give it a pattern (specifying where the submissions are) and then the inclusion/exclusion rules tell compare50 which files within the submissions specified by that pattern should be considered. This feature cannot be mimicked by writing more complex patterns because the patterns apply to different sets of things. All this to say, that the inclusion/exclusion flags serve a fundamentally different purpose in compare50 than they do in render50.

One solution could be to add another set of inclusion/exclusion flags which apply to the set of submissions you specify. This could potentially be pretty confusing. Another, which would solve Erin's issue in this particular case, but would not yield the behavior you expect in your comment would be to change slightly how we deal with submissions which are files rather than directories. I think we currently only apply these patterns to submissions that are also directories (since these are the only ones that "contain" files), but we could apply them to submissions that are single files as well (essentially treating a single-file submission the same as a folder containing that single file), and then apply the rule that if all the files within a submission are excluded, the whole submission is ignored.

**Comment by Jelleas** [comment]
Actually the default behaviour for empty submissions is to raise an error:

https://github.com/cs50/compare50/blob/9697076af7f7527bf92c88d2d4f303b678a02b13/compare50/__main__.py#L76

You would not want a submission to be accidentally and then silently ignored when using compare50 to search for plagiarism. That said, a warning instead of an error might suffice here.

I do agree with @crossroads1112. And, I like the idea of ignoring a single file submission that contains just an ignored file, but with a warning message attached.
