### ISSUE TITLE
switch color scheme of line numbers/text

### ISSUE THREAD

**Issue by dlloyd09** [cs50/compare50#23]
Code/text is gray, while line numbers are black. This should be inverted, please!

**Comment by Jelleas** [comment]
Ah! The code/text is actually black, but the ignored parts are in gray. Currently we only ignore code/text because it was either included in a distribution file or you are using a method of comparison that does not compare certain parts (comments in "structure" for instance). We keep the ignored code/text around to give you a sense of what the overall submission looks like, but for sake of plagiarism detection you should not consider any code/text that is in gray.

We are definitely open for suggestions on how to (better) explain this in a view, or for different methods of differentiating between relevant parts of code/text and ignored or not compared parts of code/text.

My inclination is to add feedback from compare50 as to why a certain part of code is deemed irrelevant. And to maybe have some kind of collapsing/hiding feature that lets you strip out everything that is ignored, and lets you more comfortably focus on the relevant parts of the code.
