### ISSUE TITLE
In match_#.html, select "exact" by default instead of "structure"

### ISSUE THREAD

**Issue by dmalan** [cs50/compare50#57]
Based on experience, we always started with "exact" when reviewing.

**Comment by Jelleas** [comment]
compare50 is by design extensible in its comparison methods, and it seems wrong to prioritize one method over another. The current logic is that the comparison method that creates the ranking, is the first in the list of views. 

But I think adressing https://github.com/cs50/compare50/issues/66 would solve this issue too.
